In [2]:
import os
import pandas as pd

# This path should be the exact path to your folder where the CSV files are located.
# The `ls` command in the terminal (or Finder on Mac) will show you the exact folder name.
folder_path = '/Users/sankalpmishra/Desktop/Projects/IPL Data/IPL_2008_to_2022_All_Match_Dataset'

# Use os.path.join to create the correct file paths
ball_by_ball_path = os.path.join(folder_path, 'IPL_Ball_by_Ball_2008_2022.csv')
matches_path = os.path.join(folder_path, 'IPL_Matches_2008_2022.csv')

# Load the data into DataFrames
ball_by_ball_df = pd.read_csv(ball_by_ball_path)
matches_df = pd.read_csv(matches_path)

In [3]:
# Display the first 5 rows of the ball_by_ball data
print("Ball-by-Ball Data:")
display(ball_by_ball_df.head())

# Get a summary of the matches data
print("\nMatches Data Info:")
matches_df.info()

# Get descriptive statistics for numerical columns in the matches data
print("\nMatches Data Description:")
display(matches_df.describe())

Ball-by-Ball Data:

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals

Matches Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB

Matches Data Description:

                 ID      Margin
count  9.500000e+02  932.000000
mean   8.304852e+05   17.056867
std    3.375678e+05   21.633109
min    3.359820e+05    1.000000
25%    5.012612e+05    6.000000
50%    8.297380e+05    8.000000
75%    1.175372e+06   19.000000
max    1.312200e+06  146.000000